"""Initialize database
Revision ID: ce2c434e84fd
Revises: 
Create Date: 2019-08-16 21:00:16.105943
"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ce2c434e84fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utility_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type_id', sa.String(), nullable=True),
    sa.Column('_geometry', geoalchemy2.types.Geometry(management=True), nullable=True),
    sa.Column('attributes', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset')),
    sa.UniqueConstraint('utility_id', 'name', name='unique_utility_asset_name')
    )
    op.create_table('asset_connection',
    sa.Column('left_asset_id', sa.String(), nullable=True),
    sa.Column('right_asset_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['left_asset_id'], ['asset.id'], name=op.f('fk_asset_connection_left_asset_id_asset')),
    sa.ForeignKeyConstraint(['right_asset_id'], ['asset.id'], name=op.f('fk_asset_connection_right_asset_id_asset'))
    )
    op.create_table('asset_content',
    sa.Column('parent_asset_id', sa.String(), nullable=True),
    sa.Column('child_asset_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_asset_id'], ['asset.id'], name=op.f('fk_asset_content_child_asset_id_asset')),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['asset.id'], name=op.f('fk_asset_content_parent_asset_id_asset'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_content')
    op.drop_table('asset_connection')
    op.drop_table('asset')
    # ### end Alembic commands ###
