def includeme(config):
    config.add_route(
        'dashboards.json',
        '/dashboards.json')
    config.add_route(
        'assets_kit.json',
        '/assetsKit.json')
    config.add_route(
        'assets.json',
        '/assets.json')
    config.add_route(
        'assets_metrics.json',
        '/assets/metrics.json')
    config.add_route(
        'assets.csv',
        '/assets.csv')
    config.add_route(
        'assets.dss',
        '/assets.dss')
    config.add_route(
        'asset.json',
        '/assets/{id}.json')
    config.add_route(
        'asset_tasks.json',
        '/assets/{id}/tasks.json')
    config.add_route(
        'asset_relation.json',
        '/assets/{id}/{key}/{otherId}.json')
    config.add_route(
        'tasks.json',
        '/tasks.json')
    config.add_route(
        'tasks_metrics.json',
        '/tasks/metrics.json')
    config.add_route(
        'task.json',
        '/tasks/{id}.json')
    config.add_route(
        'logs.json',
        '/logs.json')
    config.add_route(
        'logs_metrics.json',
        '/logs/metrics.json')
    config.add_route(
        'shape.csv',
        '/assets/{asset}/shape.csv')
